site_name: IT Top Journal API
docs_dir: documentation/src
site_dir: documentation/site

theme:
  name: material
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      accent: deep-purple
      toggle:
        icon: material/brightness-7
        name: Переключить на тёмную тему
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-purple
      accent: deep-purple
      toggle:
        icon: material/brightness-4
        name: Переключить на светлую тему
  font:
    text: Roboto
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
  icon:
    repo: fontawesome/brands/github
  logo: material/api
  favicon: material/api

repo_url: https://github.com/trapplus/ITtop-journal-api-doc
repo_name: ITtop-journal-api-doc

plugins:
  - awesome-pages
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: ru
          default: true
          name: "\U0001F1F7\U0001F1FA Русский"
          build: true
          site_name: "API Журнала ИТ Top Академии"
        - locale: en
          name: "\U0001F1EC\U0001F1E7 English"
          build: true
          site_name: "IT Top Academy Journal API"
  - swagger-ui-tag:
      supportedSubmitMethods: ["get", "put", "post", "delete", "patch"]
      docExpansion: list

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/trapplus/ITtop-journal-api-doc
