"""Tests for the Cloudflare Worker mock server template.

The worker is generated by mock/build_worker.py. We verify the template
contains the correct login-routing logic, since we can't run JS in pytest.
"""

import importlib.util
from pathlib import Path

BUILD_WORKER = Path("mock/build_worker.py")


def _load_module():
    spec = importlib.util.spec_from_file_location("build_worker", BUILD_WORKER)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_worker_template_has_login_routing():
    mod = _load_module()
    rendered = mod._render_worker({"/auth/login": {"access_token": "mock"}})

    assert 'apiPath === "/auth/login"' in rendered
    assert "proxyToRealApi(request, apiPath)" in rendered
    assert "realResp.status >= 200" in rendered


def test_worker_template_login_falls_back_to_mock():
    mod = _load_module()
    rendered = mod._render_worker({"/auth/login": {"access_token": "mock"}})

    # After try/catch for real API, must fall back to MOCK lookup
    lines = rendered.split("\n")
    login_block_started = False
    found_mock_fallback = False

    for line in lines:
        if 'apiPath === "/auth/login"' in line:
            login_block_started = True
        if login_block_started and "const payload = MOCK[apiPath]" in line:
            found_mock_fallback = True
            break

    assert found_mock_fallback, "Login block must fall back to MOCK when real API fails"


def test_worker_template_preserves_has_token_logic():
    mod = _load_module()
    rendered = mod._render_worker({"/test": {"data": 1}})

    # Normal token-based routing must still exist after login block
    assert 'request.headers.has("Authorization")' in rendered
    assert "hasToken" in rendered


def test_worker_template_login_block_precedes_token_check():
    mod = _load_module()
    rendered = mod._render_worker({"/auth/login": {"access_token": "mock"}})

    login_pos = rendered.index('apiPath === "/auth/login"')
    token_check_pos = rendered.index("if (hasToken)")
    assert login_pos < token_check_pos, "Login routing must come before token check"
