name: Publish (reusable)

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    environment: pages
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - uses: actions/download-artifact@v4
        with:
          name: examples-data
          path: data/examples/
      - run: python main.py --step publish
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation/src
          destination_dir: .
          keep_files: true
